### PR TITLE
IpmiFeaturePkg: PeiGenericIpmi - Implement RegisterForShadow

### LINKED ISSUE #308: [Bug]: PeiGenericIpmi CAR evacuation
### Is there an existing issue for this?

- [x] I have searched existing issues

### Current Behavior

In an X86 system, when PeiGenericIpmi runs the first time (while executing from cache) it will allocate memory from CAR to host the EFI_PEI_PPI_DESCRIPTOR and IPMI_BMC_INSTANCE_DATA.  The EFI_PEI_PPI_DESCRIPTOR address is copied into PEI Core internal data (https://github.com/microsoft/mu_basecore/blob/dev/202502/MdeModulePkg/Core/Pei/Ppi/Ppi.c#L511)

After memory becomes available, PPI pointers that were in CAR are converted to their new physical addresses (https://github.com/microsoft/mu_basecore/blob/dev/202502/MdeModulePkg/Core/Pei/Ppi/Ppi.c#L161C1-L161C20)

But for the internal functions in those PPIs, they still point back to the flash part.

https://github.com/microsoft/mu_basecore/blob/dev/202502/UefiCpuPkg/CpuMpPei/CpuPaging.c#L422
After memory is discovered, the page tables will mark the SPI part as not present, and this will force any entity calling into the Flash Region functions to page fault. 

### Expected Behavior

Possible solutions:

1. Change PeiGenericIpmi to shadow the PEIM, and handle fixing up the PPI descriptor.

### Steps To Reproduce

Reproduced in a vendor specific platform

### Build Environment

```markdown
- OS(s): n/a
- Tool Chain(s): VS2022
- Targets Impacted: X64 Pei
```

### Version Information

```text
Top of Tree
```

### Urgency

Low

### Are you going to fix this?

I will fix it

### Do you need maintainer feedback?

No maintainer feedback needed

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by apop5**
## Description

On platforms that use CAR, when PeiGenericIpmi runs, it will run from CAR. The PPI Descriptor will be allocated from CAR and installed in the PEI core.

When permanent memory becomes available, CAR will be torn down, and PPIs will be transitioned to permemenant memory, but the PPI functions will still point to the functions that were contained in the flash region.

When MemoryDiscoveredPpiNotifyCallback in CpuMpPei is triggered, the SPI region will be marked as not present, and any entity that attempts to access the SPI will trigger a page fault.

Modify the PeiGenericIpmi to register for shadowing (relaunch the entry point after memory is available) and modify the entry point to detect that memory is available, and to fixup the PPI descriptor to use the functions contained in the reloaded PEIM.

- [x] Impacts functionality?
- [ ] Impacts security?
- [ ] Breaking change?
- [ ] Includes tests?
- [ ] Includes documentation?

## How This Was Tested
tested in vendor specific platform that encountered a page fault with original implementation.

## Integration Instructions
No integration necessary.

### CODE REVIEW

File: IpmiFeaturePkg/GenericIpmi/Pei/PeiGenericIpmi.c [hunk 1]
```diff
@@ -54,85 +54,125 @@ PeimIpmiInterfaceInit (
   IPMI_BMC_HOB            *BmcHob;
 
   mIpmiInstance = NULL;
```
Comment (makubacki) [inline IpmiFeaturePkg/GenericIpmi/Pei/PeiGenericIpmi.c:56]: Not related to your change necessarily, but why do these local variables use the module level variable naming convention (prefixed with `m`)?

File: IpmiFeaturePkg/GenericIpmi/Pei/PeiGenericIpmi.c [hunk 2]
```diff
@@ -54,85 +54,125 @@ PeimIpmiInterfaceInit (
...
+    Status = PeiServicesLocatePpi (&gPeiIpmiTransportPpiGuid, 0, &OldPeiIpmiBmcDataDesc, (VOID **)&OldIpmiInstance);
+    if (!EFI_ERROR (Status)) {
+      // Find the existing allocation by searching memory pool hobs
+      Hob.Raw = GetHobList ();
+      while ((Hob.Raw = GetNextHob (EFI_HOB_TYPE_MEMORY_POOL, Hob.Raw)) != NULL) {
+        // Calculate the correct pointer to the IPMI instance data
+        // The Pool HOB contains the data immediately after the HOB header
+        OldIpmiInstance = (IPMI_BMC_INSTANCE_DATA *)(Hob.Pool + 1);
+
+        if (OldIpmiInstance->Signature == SM_IPMI_BMC_SIGNATURE) {
```
Comment (makubacki) [inline IpmiFeaturePkg/GenericIpmi/Pei/PeiGenericIpmi.c:155]: This seems a little more dangerous than using a more formal lookup in the heap like a GUID HOB. You might want to check that the HOB pool length (I think would be `Hob.Pool->Header->HobLength - sizeof (EFI_HOB_MEMORY_POOL)`) is at least the size of `IPMI_BMC_INSTANCE_DATA.Signature` (`UINTN`) before checking the signature value. The HOB length should at least be a byte in size to my understanding, but `UINTN` could obviously be larger.

**Review by makubacki — APPROVED** [review]

File: IpmiFeaturePkg/GenericIpmi/Pei/PeiGenericIpmi.c (hunk 1 above)
Comment (apop5) [reply IpmiFeaturePkg/GenericIpmi/Pei/PeiGenericIpmi.c:56]: Pushing a change to drop the m prefixes for the Pei.

Comment (apop5) [reply IpmiFeaturePkg/GenericIpmi/Pei/PeiGenericIpmi.c]: fixed in latest

**Review by cfernald — APPROVED** [review]
